# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Joy Chen
tagline:          'The personal website of Joy Chen'
url:              http://joyvchen.github.io
paginate:         1
baseurl:          /
author:
  name:           'Joy Chen'
  url:            https://twitter.com/chenjoyv
  email:          chenjoyv@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/joyvchen
pages_list:       {'About':'/about','Archive':'/archive'}
